backend:
  name: github
  repo: asmaneh/asmaneh.github.io # Path to your GitHub repository
media_folder: 'upload/img'

collections:
  - name: 'site_settings'
    label: 'Site settings'
    files:
      - label: 'Site settings'
        name: 'site'
        file: '_data/site.yml'
        fields:
          - label: 'Tel'
            name: 'tel'
            width: 'string'
